name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          diffutils
          make
          nasm
          yasm
        path-type: inherit
        update: true

    - name: Setup MSYS2
      shell: msys2 {0}
      run: mv /usr/bin/link.exe /usr/bin/link.exe.bak
        
    - name: Clone AAC
      shell: cmd
      run: |
        mkdir upload
        git clone https://github.com/mstorsjo/fdk-aac.git
        cd fdk-aac
        git checkout v2.0.3

    - name: Clone FFmpeg
      shell: cmd
      run: |
        git clone https://github.com/faojdoai324234s/FFmpeg.git
        cd FFmpeg
        git checkout e038a48d08b9c3768168eec11a741d1ddc69ee8a

    - name: Configure FFmpeg
      working-directory: ${{github.workspace}}/FFmpeg
      shell: msys2 {0}
      env:
        UPLOAD_FOLDER: ${{github.workspace}}\upload
        FDKAAC_FOLDER: ${{github.workspace}}\fdk-aac
      run: |
        CC=cl
        ./configure \
        --arch=x86_64 \
        --target-os=win64 \
        --toolchain=msvc \
        --prefix=$UPLOAD_FOLDER \
        --enable-gpl \
        --enable-nonfree \
        --disable-static \
        --enable-shared \
        --disable-all \
        --disable-everything \
        --disable-doc \
        --enable-avcodec \
        --enable-avformat \
        --enable-swresample \
        --enable-w32threads \
        --enable-error-resilience \
        --enable-decoder=aac \
        --enable-demuxer=aac \
        --enable-parser=aac \
        --disable-decoder=libdav1d \
        --enable-libfdk-aac \
        --enable-d3d11va \
        --enable-d3d12va \
        --enable-dxva2 \
        --disable-iconv \
        --disable-zlib \
        --disable-debug

    - name: Compile FDKAAC
      shell: cmd
      working-directory: ${{github.workspace}}/fdk-aac
      run: |
        echo "Building Debug..."
        cmake -B build -D CMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug
        rmdir /s /q build
        echo "Building Release..."
        cmake -B build -D CMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
